# Generated by Django 3.0.6 on 2020-07-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainProgram', '0002_storeurl_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeurl',
            name='short_url',
        ),
    ]
